name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Триггер на пуш в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/tennis-booking-bot
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy tennis-booking-bot \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/tennis-booking-bot \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated